### ISSUE TITLE
Cannot start Cadence, loadlocale.c related error

### ISSUE THREAD

**Issue by Spleenico** [falkTX/Cadence#221]
Hi Filipe,
Yesterday I wanted to install the current Linux 64 version of Cadence (Cadence-0.8.1-linux64.tar.xz if you did not update it in the last 12 hours), but I got a locale error that looked very similar to https://github.com/falkTX/Carla/issues/623.
Do you expect indeed the same error?
It was late yesterday and I closed down the laptop before doing the bug report. 
If you do not expect the same error, I will check tonight when back to my Linux laptop what the error message exactly is and paste it here.

**Comment by Spleenico** [comment]
Here is the output

> spleenico@spleenico-XPS-L322X:~/Downloads/Cadence-0.8.1$ ./Cadence
> Cadence: loadlocale.c:130: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.
> Aborted (core dumped)

**Comment by falkTX** [comment]
Cadence is still maintained of course, I just cant fix this issue without a major overhaul of how these binaries are produced. (because of the move to Qt5)
So likely the issue with those binaries won't be fixed. Probably I will just stop producing such binaries for linux, as there is nothing special to get cadence running anyway. And the binaries are quite limited in functionality anyway, so not that useful in the end. (too much work for very little gain).

**Comment by Spleenico** [comment]
Thanks Filipe for your answer. I understand the ratio benefit / effort is too little to be worth it.
Maybe good to add a little warning on your kxstudio download page. Cheers. :)

**Comment by marianajo** [comment]
I had the same issue as @Spleenico. Is there any workaround to use Cadence, anyway?

**Comment by Spleenico** [comment]
Thanks Filipe, as far I am am concerned, the ticket is closed.
