### ISSUE TITLE
Claudia: Non-Mixer strips not showing up.

### ISSUE THREAD

**Issue by ghost** [falkTX/Cadence#90]
If you ad multiple mixer strips to Non-Mixer only the first created will show up in Claudia.
With Catia or Carla all created non-mixer strips are visible.

**Comment by ViktorNaworski** [comment]
I finally found a nice workaround for this issue, with Claudia 0.8.1 and Non-Mixer 1.2.0, that i want to share here, since this is the first result that the usual search-engines spit out.
It allows starting Non-Mixer with Claudia/Ladish with showing all strips and even with every created Group separately:
In Claudia, right-click your session or a room, then go on "Run Custom..." and enter the command:
$(non-mixer &disown)
And name it as you wish.
You can also use it with arguments like:
$(non-mixer --osc-port <portnum> <path_to_project> &disown)
With this little workaround, for me, Ladish/Claudia comes back to live, since Non-Mixer is a really powerful and efficient piece of Software!
